---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: admin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: admin:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: admin-env
      terminationGracePeriodSeconds: 180