---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: api-gateway-env
      terminationGracePeriodSeconds: 180