---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: main
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: main:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: main-env
      terminationGracePeriodSeconds: 180